
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.actix]
url = "https://raw.githubusercontent.com/actix/supply-chain/main/audits.toml"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.aead]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.3"
criteria = "safe-to-deploy"

[[exemptions.aes-kw]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.argon2]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.async-broadcast]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.async-channel]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.async-executor]]
version = "1.13.2"
criteria = "safe-to-deploy"

[[exemptions.async-io]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.async-lock]]
version = "3.4.0"
criteria = "safe-to-deploy"

[[exemptions.async-process]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.async-recursion]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.async-signal]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.async-task]]
version = "4.7.1"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-rs]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-sys]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.axum]]
version = "0.7.9"
criteria = "safe-to-deploy"

[[exemptions.axum-core]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base32]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.7.3"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.blake2]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.11.0-rc.5"
criteria = "safe-to-deploy"

[[exemptions.block-padding]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.blocking]]
version = "1.6.1"
criteria = "safe-to-deploy"

[[exemptions.cbc]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.cbindgen]]
version = "0.29.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.42"
criteria = "safe-to-deploy"

[[exemptions.clang-sys]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.concurrent-queue]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.configparser]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.console-api]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.console-subscriber]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.cookie]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.cookie_store]]
version = "0.21.1"
criteria = "safe-to-deploy"

[[exemptions.cookie_store]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-channel]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.dbus]]
version = "0.9.9"
criteria = "safe-to-deploy"

[[exemptions.dbus-crossroads]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.dbus-tokio]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.der_derive]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.3"
criteria = "safe-to-deploy"

[[exemptions.devd-rs]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.dtoa-short]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.16.9"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.ego-tree]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.endi]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.enumflags2]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.enumflags2_derive]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "5.4.0"
criteria = "safe-to-deploy"

[[exemptions.event-listener-strategy]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.fallible-streaming-iterator]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.file-id]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.flagset]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.fsevent-sys]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.futf]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.futures-lite]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ghash]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.hdrhistogram]]
version = "7.5.4"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.4"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.13.0-rc.0"
criteria = "safe-to-deploy"

[[exemptions.hostname]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.hostname-validator]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.html5ever]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.hybrid-array]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.hyper-rustls]]
version = "0.27.5"
criteria = "safe-to-deploy"

[[exemptions.hyper-timeout]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.inotify]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.inotify-sys]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.iri-string]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.kbkdf]]
version = "0.0.1"
criteria = "safe-to-deploy"

[[exemptions.kqueue]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.kqueue-sys]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.lazycell]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.libdbus-sys]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.libnss]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.0.1"
criteria = "safe-to-deploy"

[[exemptions.libsqlite3-sys]]
version = "0.25.2"
criteria = "safe-to-deploy"

[[exemptions.libudev]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.libudev-sys]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.lru-slab]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.mac]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.malloced]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.markup5ever]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.match_token]]
version = "0.35.0"
criteria = "safe-to-deploy"

[[exemptions.matchit]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.md4]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.notify]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.notify-debouncer-full]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.notify-types]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.num-bigint-dig]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.num_enum]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.num_enum_derive]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.num_threads]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.oauth2]]
version = "5.0.0"
criteria = "safe-to-deploy"

[[exemptions.oid]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.openidconnect]]
version = "4.0.1"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-http]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-otlp]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-proto]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry-semantic-conventions]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.ordered-stream]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.os-release]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.p384]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.password-hash]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.pastey]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.peg]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.peg-macros]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.peg-runtime]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.picky-asn1]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.picky-asn1]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.picky-asn1-der]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.picky-asn1-der]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.picky-asn1-x509]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.piper]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.pkcs1]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.polling]]
version = "3.7.4"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.prost]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-derive]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.prost-types]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.psl-types]]
version = "2.0.11"
criteria = "safe-to-deploy"

[[exemptions.publicsuffix]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.quinn]]
version = "0.11.8"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.11.12"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.12"
criteria = "safe-to-deploy"

[[exemptions.reqwest_cookie_store]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rpassword]]
version = "7.4.0"
criteria = "safe-to-deploy"

[[exemptions.rsa]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.rtoolbox]]
version = "0.0.3"
criteria = "safe-to-deploy"

[[exemptions.runloop]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.rusqlite]]
version = "0.27.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.12.0"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.27"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.scraper]]
version = "0.24.0"
criteria = "safe-to-deploy"

[[exemptions.sd-notify]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.14.0"
criteria = "safe-to-deploy"

[[exemptions.selectors]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.serde_plain]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.servo_arc]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.sha-crypt]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.5"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.smartstring]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.sshkeys]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.string_cache]]
version = "0.8.9"
criteria = "safe-to-deploy"

[[exemptions.string_cache_codegen]]
version = "0.5.4"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.system-configuration]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.system-configuration-sys]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.systemd-journal-logger]]
version = "2.2.2"
criteria = "safe-to-deploy"

[[exemptions.tendril]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.24"
criteria = "safe-to-deploy"

[[exemptions.tls_codec]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.tls_codec_derive]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.2"
criteria = "safe-to-deploy"

[[exemptions.tonic]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.tracing-forest]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.tss-esapi]]
version = "8.0.0-alpha"
criteria = "safe-to-deploy"

[[exemptions.tss-esapi-sys]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.uds_windows]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.urlencoding]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.utf-8]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.utoipa]]
version = "4.2.3"
criteria = "safe-to-deploy"

[[exemptions.utoipa-gen]]
version = "5.4.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.18.1"
criteria = "safe-to-deploy"

[[exemptions.uzers]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-futures]]
version = "0.4.50"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.web_atoms]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.11"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.x509-cert]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.zbus_names]]
version = "4.2.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.25"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.25"
criteria = "safe-to-deploy"

[[exemptions.zvariant]]
version = "5.5.3"
criteria = "safe-to-deploy"

[[exemptions.zvariant_derive]]
version = "5.5.3"
criteria = "safe-to-deploy"

[[exemptions.zvariant_utils]]
version = "3.2.0"
criteria = "safe-to-deploy"
