name: Stale Checker
permissions:
  issues: write
  pull-requests: write

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Stale Issue
        uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had recent activity. 
            If no further activity occurs, it will be closed in 7 days. 
            Thank you for your contributions!
          stale-pr-label: 'stale'
          days-before-stale: 60
          days-before-close: 7
          operations-per-run: 100
          exempt-draft-pr: true
          only-issue-types: 'Bug'
          exempt-issue-labels: 'stale exempt'
          exempt-pr-labels: 'stale exempt'
          exempt-all-pr-assignees: true
